version: '3'

services:
  dsi_spring:
    build:
      context: ./.docker/java
      dockerfile: Dockerfile
    container_name: spring_boot_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - dsi_postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/dsi-meeting-management
      SPRING_DATASOURCE_USERNAME: dsi
      SPRING_DATASOURCE_PASSWORD: dsi
    volumes:
      - .m2:/root/.m2

  dsi_postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dsi
      POSTGRES_PASSWORD: dsi
      POSTGRES_DB: dsi-meeting-management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
