version: '3.8'

services:
  dsi_spring:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: spring_boot_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - dsi_postgres
    environment:
      - spring.datasource.url=jdbc:postgresql://dsi_postgres:5432/dsi-meeting-management
      - spring.datasource.username=dsi
      - spring.datasource.password=dsi

  dsi_postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dsi
      POSTGRES_PASSWORD: dsi
      POSTGRES_DB: dsi-meeting-management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
